name: Deploy Azure Static Web Apps

on:
  push:
    branches:
      - feature/migration_azure_swa # TODO: mainブランチに変更
    paths:
      - .github/workflows/deploy-swa.yaml
      - .github/workflows/reusable-deploy-swa.yaml
      - src/**
      - components.json
      - index.html
      - package*.json
      - postcss.config.js
      - resources/base.bicep
      - staticwebapp.config.json
      - tailwind.config.js
      - tsconfig*.json
      - vite.config.ts

jobs:
  use-deploy-swa-workflow:
    uses: ./.github/workflows/reusable-deploy-swa.yaml
    with:
      API_URI: ${{ vars.API_URI }}
      AZURE_AD_SP_CONTRIBUTOR_CLIENT_ID: ${{ vars.AZURE_AD_SP_CONTRIBUTOR_CLIENT_ID }}
      AZURE_AD_SP_MSAL_CLIENT_ID: ${{ vars.AZURE_AD_SP_MSAL_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      SWA_NAME: ${{ vars.SWA_NAME }}
    secrets:
      AZURE_AD_SP_CONTRIBUTOR_CLIENT_SECRET: ${{ secrets.AZURE_AD_SP_CONTRIBUTOR_CLIENT_SECRET }}
